name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "81f2b0ad-d3dc-4c74-9474-bb7e653a0133"
migrations_dir = "./migrations"

# [ai]
# binding = "AI"

[[r2_buckets]]
bucket_name = "blazenote"
binding = "blazenote"

[observability.logs]
enabled = true
